### ISSUE TITLE
inaccurate output while monitoring FTP site

### ISSUE THREAD

**Issue by rcbathina** [esterniclos/nagios_iis#1]
Hi,
Though the FTP site is up and running. I am getting critical alert with this plugin.
No issues with http sites. Any idea?

**Comment by esterniclos** [comment]
Thank you for your message. 

For some reason powershell library does not provide with state information when it is a FTP site.

This is how I tested it. It would be great if you could give some feedback if it works the same in your system.

In my powershell console 

```
Import-Module WebAdministration
$sm = [Microsoft.Web.Administration.ServerManager]::OpenRemote("localhost")
$sm.Sites
```

I my list of sites, I had my ftp site with name myftp but with no state:

```
ApplicationDefaults        : Microsoft.Web.Administration.ApplicationDefaults
Applications               : {myftp/}
Bindings                   : {[ftp] *:21:}
(..)
Name                       : myftp
(..)
State                      :
```

It's not Started, neither stopped. I've changed output so that now it's unknown.

I'd recommend you to use a simple check from nagios that tries via telnet (p.e.) server's port 21. 

I haven't tried these, but look like they deserve a try:

https://exchange.nagios.org/directory/Plugins/Network-Protocols/FTP
